# Generated by Django 5.0.3 on 2024-05-18 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foto_crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumphoto',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foto_crud.user'),
            preserve_default=False,
        ),
    ]
